#!/bin/bash

if [ -n "$DEBUG" ] ; then
    set -x
fi

here="$(cd $(dirname $0) && pwd)"

. $here/opennebula-common

echo "Running cloud-init with user data"

if [ -z "$USER_DATA" ] ; then
    if [ -z "$EC2_USER_DATA" ] ; then
        echo "No user data, leaving."
        exit 0
    fi
    USER_DATA="$(echo $EC2_USER_DATA | base64 -d)"
fi

user_data="$(mktemp /tmp/user-data-XXXXXX.yml)"

if [ "$USER_DATA_ENCODING" = "base64" ] ; then
    echo "$USER_DATA" | base64 -d > $user_data
else
    echo "$USER_DATA" > $user_data
fi

set -e
coreos-cloudinit --from-file $user_data --validate
coreos-cloudinit --from-file $user_data
